import type { Metadata } from "next";
import { Geist, Geist_Mono,Roboto } from "next/font/google";
// @ts-ignore - CSS side-effect import has no type declarations
import "./globals.css";
import NavBar from "./NavBar";
import { Suspense } from "react";
import AuthProvider from "./auth/Provider";
import { GoogleAnalytics } from '@next/third-parties/google'
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto=Roboto(
  {
    subsets:['vietnamese'],
    weight:['700','500'],
    
  }
)
const localFonts = localFont({
  src:"../public/fonds/Google_Sans/static/GoogleSans_17pt-Bold.ttf"
  
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <GoogleAnalytics gaId="G-JP2BN75F6Q" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NavBar />
          <main className={localFonts.className}>
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
